/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import {
  MatchResults,
} from '@stencil/router';

import {
  AppHome as AppHome
} from './components/app-home/app-home';

declare global {
  interface HTMLAppHomeElement extends AppHome, HTMLElement {
  }
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };
  interface HTMLElementTagNameMap {
    "app-home": HTMLAppHomeElement;
  }
  interface ElementTagNameMap {
    "app-home": HTMLAppHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-home": JSXElements.AppHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHomeAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  AppSearch as AppSearch
} from './components/app-search/app-search';

declare global {
  interface HTMLAppSearchElement extends AppSearch, HTMLElement {
  }
  var HTMLAppSearchElement: {
    prototype: HTMLAppSearchElement;
    new (): HTMLAppSearchElement;
  };
  interface HTMLElementTagNameMap {
    "app-search": HTMLAppSearchElement;
  }
  interface ElementTagNameMap {
    "app-search": HTMLAppSearchElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-search": JSXElements.AppSearchAttributes;
    }
  }
  namespace JSXElements {
    export interface AppSearchAttributes extends HTMLAttributes {
      members?: any[];
    }
  }
}


import {
  AppShow as AppShow
} from './components/app-show/app-show';

declare global {
  interface HTMLAppShowElement extends AppShow, HTMLElement {
  }
  var HTMLAppShowElement: {
    prototype: HTMLAppShowElement;
    new (): HTMLAppShowElement;
  };
  interface HTMLElementTagNameMap {
    "app-show": HTMLAppShowElement;
  }
  interface ElementTagNameMap {
    "app-show": HTMLAppShowElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-show": JSXElements.AppShowAttributes;
    }
  }
  namespace JSXElements {
    export interface AppShowAttributes extends HTMLAttributes {
      match?: MatchResults;
      members?: any[];
    }
  }
}


import {
  MyApp as MyApp
} from './components/my-app/my-app';

declare global {
  interface HTMLMyAppElement extends MyApp, HTMLElement {
  }
  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };
  interface HTMLElementTagNameMap {
    "my-app": HTMLMyAppElement;
  }
  interface ElementTagNameMap {
    "my-app": HTMLMyAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-app": JSXElements.MyAppAttributes;
    }
  }
  namespace JSXElements {
    export interface MyAppAttributes extends HTMLAttributes {
      
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
